name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 1

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake CMakeLists.txt
      
    - name: Make Build
      run: make
      
    - name: Run Test
      run: ./test1
